# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_choice', models.CharField(choices=[('cat', 'CAT'), ('kitten', 'KITTEN'), ('dog', 'DOG'), ('puppy', 'PUPPY')], default='dog', max_length=2)),
            ],
        ),
    ]
