# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 11:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_animal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Animal',
            new_name='Pet',
        ),
    ]
