# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170306_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_choice',
            field=models.CharField(choices=[('cat', 'Cat'), ('kitten', 'Kitten'), ('dog', 'Dog'), ('puppy', 'Puppy')], default='dog', max_length=10),
        ),
    ]
